### PR TITLE
feat: add github actions for release

### PR DESCRIPTION
**Pull request by Yiyiyimu**
Signed-off-by: yiyiyimu <wosoyoung@gmail.com>

Mentioned in #116

I think we could add a Github Actions to automize the version release. It could also work for other repos of api7 that need to upload to luarocks.

The process would be like, whenever we push a new **tag**, it would upload the new release on github and also upload rockspec to luarocks.

**One thing to discuss** is that, do we need to bind the release action to PR, say when we have a release PR tagged with "Release", when it got merged, the action would be triggered to create a tag, and do the rest. 
It would be more convenient, but we need an extra PR when changing release larger change, say from 1.4.3 to 1.5. Ref: https://github.com/anothrNick/github-tag-action

**TODO**
- [x] test on personal repo to make sure it works
- [x] ask @membphis for upload luarocks token

### CODE REVIEW

**Comment by membphis** [comment]
> * ask @membphis for upload luarocks token

already done

**Comment by Yiyiyimu** [comment]
@membphis PTAL

I think it works for now since I test it in my own repo and it works fine (see [workflow in my repo](https://github.com/Yiyiyimu/GithubActionsTest/runs/1848183069?check_suite_focus=true))

Also plz make sure the token name in secrets is `LUAROCKS_TOKEN`

**Comment by Yiyiyimu** [comment]
CI could be fixed with #120

**Comment by membphis** [comment]
> Also plz make sure the token name in secrets is `LUAROCKS_TOKEN`

you can take a look

image

**Comment by Yiyiyimu** [comment]
> you can take a look

Thanks a lot for the help! 

CI has passed and I think it could be reviewed~

**Review by membphis — APPROVED** [review]

**Comment by membphis** [comment]
we can make a try when we release a new version next time

**Pull request merged**
