### PR TITLE
fix: fixed the .travis parsing failure

### PR DESCRIPTION
**Pull request by tokers**
Fixed https://github.com/api7/lua-resty-etcd/issues/90.

### CODE REVIEW

**Review by membphis — APPROVED** [review]

**Comment by tokers** [comment]
@membphis Still need to wait for the travis CI, it's so slow.

**Comment by membphis** [comment]
we can check the ENV in shell script

**Comment by membphis** [comment]
help you to rerun one of the CI job

**Comment by membphis** [comment]
many thx, @tokers merge already

**Pull request merged**
