### PR TITLE
fixed  not support complex domain names

### LINKED ISSUE #83: support complex domain names
> https://github.com/api7/lua-resty-etcd/blob/master/lib/resty/etcd/v3.lua#L146-L148

- This regular expression verification does not support complex domain names

example： 

 -  http://gateway-etcd-headless.test.svc.cluster.local:2379

### PR DESCRIPTION
**Pull request by dickens7**

### CODE REVIEW

**Comment by ShiningRush** [comment]
You need change test case to match new regex.

**Comment by membphis** [comment]
> Our team also encounter same problem, this is a useful PR.

yes, I know, after this PR was merged, then we can release a new version.

**Comment by dickens7** [comment]
I don’t know how to solve it when writing test cases `no resolver defined to resolve`

**Comment by membphis** [comment]
@dickens7 CI is broken. please wait for more time.

**Comment by dickens7** [comment]
Refer to #92 wrote a test case

**Comment by membphis** [comment]
need to fix this issue first: https://github.com/api7/lua-resty-etcd/issues/93

> Refer to #92 wrote a test case

seems that #92 and #85 are fixing the same problem?

**Comment by dickens7** [comment]
> seems that #92 and #85 are fixing the same problem?

right!

**Comment by membphis** [comment]
@dickens7 https://github.com/api7/lua-resty-etcd/pull/92 has been merged.

so I think we can close this PR. many thx @dickens7's contributions.

**Pull request closed without merging**
