### PR TITLE
feat: support serializer option in v3 api

### PR DESCRIPTION
**Pull request by membphis**

### CODE REVIEW

**Comment by Gerrard-YNWA** [comment]
ping @membphis 
CI passed and I think this pr is ready for review : )

**Comment by membphis** [comment]
@Yiyiyimu @nic-chen welcome to look at this PR

**Review by spacewander — APPROVED** [review]

**Comment by nic-chen** [comment]
Add a test case for default serializer should be better. @Gerrard-YNWA

**Review by nic-chen — APPROVED** [review]

**Comment by nic-chen** [comment]
merged. Thanks a lot. @Gerrard-YNWA

**Pull request merged**
